/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricauthentication;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Lahiru
 */
public class AuthenticationUi extends javax.swing.JFrame {

    JComponent[] coms = new JComponent[12];
private boolean isImageSelected = false;
    public AuthenticationUi() {
        initComponents();
        fileSelect.setVisible(false);

        for (int i = 0; i < 12; i++) {
            JComponent com = new DraggableComponent();
            com.setBorder(new LineBorder(Color.white));
            com.setSize(17, 17);
            com.setBackground(Color.black);
            com.setLocation(i + 20 * i, 0);

            JLabel num = new JLabel(i + 1 + "");
            num.setForeground(Color.white);
            num.setSize(16, 16);
            num.setHorizontalTextPosition(0);
            com.add(num);

            coms[i] = com;
            this.add(com, 10);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSelect = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TbtnSelectImage = new javax.swing.JToggleButton();
        lblHand = new javax.swing.JLabel();
        BtnInsert = new javax.swing.JButton();
        BtnValidate = new javax.swing.JButton();
        txtUname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 700));
        setSize(new java.awt.Dimension(960, 700));
        getContentPane().setLayout(null);

        fileSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSelectActionPerformed(evt);
            }
        });
        getContentPane().add(fileSelect);
        fileSelect.setBounds(470, 40, 470, 360);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 22, 20, 16);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 22, 20, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(44, 22, 20, 16);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(64, 22, 20, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(84, 22, 20, 16);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(106, 22, 20, 16);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(126, 22, 20, 16);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(146, 22, 20, 16);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(169, 22, 20, 16);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 40, 900, 12);

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(450, 60, 10, 520);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(189, 22, 20, 16);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hand2.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(480, 85, 408, 513);

        TbtnSelectImage.setText("Select Image");
        TbtnSelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnSelectImageActionPerformed(evt);
            }
        });
        getContentPane().add(TbtnSelectImage);
        TbtnSelectImage.setBounds(450, 10, 123, 29);

        lblHand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHand.setMaximumSize(new java.awt.Dimension(408, 513));
        lblHand.setMinimumSize(new java.awt.Dimension(408, 513));
        lblHand.setPreferredSize(new java.awt.Dimension(408, 513));
        getContentPane().add(lblHand);
        lblHand.setBounds(20, 85, 410, 500);

        BtnInsert.setText("Sign Up");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert);
        BtnInsert.setBounds(360, 10, 92, 29);

        BtnValidate.setText("Validate");
        BtnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValidateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnValidate);
        BtnValidate.setBounds(350, 595, 94, 29);

        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtUname);
        txtUname.setBounds(220, 595, 130, 26);

        jLabel11.setText("User Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 600, 80, 16);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("11");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(212, 22, 20, 16);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("12");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(234, 22, 20, 16);

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Place the points in the selected image as shown in the sample image");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 50, 440, 16);

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Sample Image");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(600, 50, 100, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbtnSelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnSelectImageActionPerformed
        if (TbtnSelectImage.isSelected() == true) {
            fileSelect.setVisible(true);
        } else {
            fileSelect.setVisible(false);
        }
    }//GEN-LAST:event_TbtnSelectImageActionPerformed

    private void fileSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSelectActionPerformed

        File file = fileSelect.getSelectedFile();
        if (file != null) {

            try {
                BufferedImage image = ImageIO.read(file);
                BufferedImage resizedImage = ResizeImage.resize(image, 408, 513);
                lblHand.setIcon(new ImageIcon(resizedImage));
                isImageSelected = true;
            } catch (IOException e) {
                e.printStackTrace();
                isImageSelected = false;
            }
        }

    }//GEN-LAST:event_fileSelectActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        if (isImageSelected) {
            Hand hand = new HandHandler().getHand(coms);
            if (hand == null) {
                JOptionPane.showMessageDialog(this, "Mark the points as shown in the image", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            new SignupPage(hand, this, true).setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Select Image!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValidateActionPerformed
      if (!txtUname.getText().isEmpty()) {
            Hand hand = new HandHandler().getHand(coms);
            if (hand == null) {
                return;
            }
            hand.setUserId(txtUname.getText());
            boolean b = SecurityHandler.checkForMatch(hand);
            if (b) {
                JOptionPane.showMessageDialog(this, "Permission Granted", "Succesfull",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No matched hand is found!", "Invalid",
                        JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "User name cannot be empty", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnValidateActionPerformed

    private void txtUnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyTyped
       if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            // do not allow to enter space
            evt.consume();
        }

    }//GEN-LAST:event_txtUnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnValidate;
    private javax.swing.JToggleButton TbtnSelectImage;
    private javax.swing.JFileChooser fileSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHand;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables


}
